name: Build and Upload APK to GitHub Release

on:
    release:
        types: [published]

jobs:
    android-build:
        name: Android Build
        if: startsWith(github.event.release.tag_name, 'mobile-')
        runs-on: ubuntu-latest
        env:
          APP_SCHEME: ${{ secrets.APP_SCHEME }}
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          APP_NAME: ${{ secrets.APP_NAME }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install Dependencies
              run: yarn install

            - name: Prebuild the Native Directory
              run: cd apps/mobile && npx expo prebuild --platform android --no-install --clean

            - name: Cache Gradle Wrapper
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                    ${{ runner.os }}-gradle-wrapper-

            - name: Cache Gradle Dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                    ${{ runner.os }}-gradle-caches-

            - name: Make Gradlew executable
              run: cd apps/mobile/android && chmod +x ./gradlew

            - name: Build Android Release
              run: |
                cd apps/mobile/android && ./gradlew clean && ./gradlew assembleRelease
                    
            - name: Upload APK to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                files:  apps/mobile/android/app/build/outputs/apk/release/app-release.apk
              env:
                GITHUB_TOKEN: ${{ secrets.RICK_MORTY_RELEASE_PLEASE_TOKEN }}